### ISSUE TITLE
Out of Memory Error

### ISSUE THREAD

**Issue by MFamStory** [sd6352051/android-image-picker#2]
Many photo load  :  OutOfMemory error

Solution 1 :
PhotosAdapter.java add to this code 

@Override
    public void onViewRecycled(ViewHolder holder) {
        super.onViewRecycled(holder);
        Glide.clear(holder.mImageView);
    }

Solution 2 : 

GalleryFragment.java 
mGalleryView.setItemViewCacheSize(N);  (Screen size X 3)

So Good Image Picker !!

**Comment by litao0621** [comment]
hi @MFamStory. unable recurring problems . 
 Can you paste the complete log info?

perhaps you can create a pull request

**Comment by litao0621** [comment]
hi @MFamStory 
Solution 1 is great 
send a pull request

``` java
@Override
public void onViewRecycled(ViewHolder holder) {
super.onViewRecycled(holder);
ViewHolder vh = (ViewHolder ) holder;
requestManager.clear(vh.mImageView);
}
```

**Comment by MFamStory** [comment]
Hi @sd6352051 
my English unskillful..  T^T

Your library is well used.
Thank you !
